### ISSUE TITLE
.skmo format specifications

### ISSUE THREAD

**Issue by Dene33** [yul85/movingcam#2]
As I understand .skmo contains the data converted from the VIBE output. I was not able to find any related scripts or descriptions of how it's done. Would be great to have some details about it. Thanks!

**Comment by yul85** [comment]
Yes, you are right. The .skmo file is the result of solving IK with joint positions obtained from VIBE output ("vibe_output.pkl"). 
You can get .skmo by using this code: movingcam/ik/get_bvh_from_vibe_limited_v2.py
