### ISSUE TITLE
Is it possible to use this repo with a Windows 10 machine?

### ISSUE THREAD

**Issue by torrinworx** [yul85/movingcam#6]
I'm trying to get this repo to work with my Windows 10 machine and was wondering what limitations I might face and if anyone has any recommendations?

Thank you for making this awesome repo public, such amazing work!

**Comment by Rahmyyy** [comment]
@torrinworx I am also keen to get this working in windows 10. I have stated to run this in linux (Ubuntu) and am having a few issues at the moment hopefully one of these options will allow for this to run. Please let us know if you have any success on windows.
