### ISSUE TITLE
make error - nlopt.hpp: No Such file or directory

### ISSUE THREAD

**Issue by Rahmyyy** [yul85/movingcam#7]
Hi, I am following the installation instructions using UBUNTU  running on wsl on windows 10. 
I run the command ''$ make -j4" and get the error below.

------------------
[ 70%] Built target dart-optimizer-ipopt
[ 71%] Building CXX object dart/optimizer/nlopt/CMakeFiles/dart-optimizer-nlopt.dir/NloptSolver.cpp.o
In file included from /home/rr/DynMo/dart-ltspd/dart/optimizer/nlopt/NloptSolver.cpp:35:
/home/rr/DynMo/dart-ltspd/dart/optimizer/nlopt/NloptSolver.hpp:36:10: fatal error: nlopt.hpp: No such file or directory
   36 | #include <nlopt.hpp>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [dart/optimizer/nlopt/CMakeFiles/dart-optimizer-nlopt.dir/build.make:63: dart/optimizer/nlopt/CMakeFiles/dart-optimizer-nlopt.dir/NloptSolver.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2273: dart/optimizer/nlopt/CMakeFiles/dart-optimizer-nlopt.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
----------------------

Any assistance is appreciated.

**Comment by drag4u** [comment]
git clone https://github.com/stevengj/nlopt.git
cd nlopt
mkdir build
cd build
cmake ..
make
sudo make install

**Comment by Rahmyyy** [comment]
Thank you @drag4u for your clear instructions and help. This has fixed this issue.
