### ISSUE TITLE
ppo algorithm training speed is very slow

### ISSUE THREAD

**Issue by JiahongWu1995** [yul85/movingcam#8]
Hello,I am very interesting in your excellenct work!
I found that the training speed of the ppo algorithm is very slow, about 7 seconds per iteration. Is there any way to improve the training speed？thank you！

**Comment by JiahongWu1995** [comment]
@yul85

**Comment by yul85** [comment]
Hello. 
We used physics simulation in our framework. And this is the main time consuming factor.
If so, we have an option to reduce the time step of the simulation, but it makes the system unstable. Thus the way reducing the time step is not recommanded. For now, I can't think of a decent way to speed it up for our framework. 
If you find a good way to make ppo training faster, please let me know.
Thank you.
