### ISSUE TITLE
speed issue !

### ISSUE THREAD

**Issue by kotaxyz** [yul85/movingcam#9]
thanks alot for this awesome work , i just want to ask why this step using get_bvh_from_vibe_limited_v2.py is slow also its not utilizing my cpu or gpu power it just uses arround 7 % of cpu and its slow , how can i increase the speed 

![Screenshot (59)](https://github.com/yul85/movingcam/assets/105466290/1443f3e3-3f71-4c92-8ec0-4d791892b38a)

**Comment by yul85** [comment]
Yeah, it's a bit slow because it solve IK and render the resulting pose every frame.
You might try to implement the code without rendering for speed up.

**Comment by kotaxyz** [comment]
@yul85  thanks alot for your reply , also i have a problem it dosnt output anything after it finishes it only shows the motion in the dart viewer  , im not an expert but i checked the code i havn't found the issue  
i'm talking about this step
Run "ik/get_bvh_from_vibe_limited_v2.py" to get the IK result ([motion_name].skmo) from step 3.

**Comment by yul85** [comment]
If your video_name is "dance",
You can find the file named "dance_vibe_dof_limit_v2.skmo" in the directory "data/vibe/dance/".

**Comment by kotaxyz** [comment]
@yul85 its still missing , i searched for it on everyplace but havnt found it
![Screenshot (60)](https://github.com/yul85/movingcam/assets/105466290/041e0c9e-e4c0-4a5a-9c39-c338d2e831ed)

**Comment by kotaxyz** [comment]
i added print lines but it dosnt even execute them 

https://github.com/yul85/movingcam/assets/105466290/14902d61-45fb-44ba-9560-1fffe854557c

**Comment by yul85** [comment]
Comment out 6 lines below Fl.run() and try it again.

**Comment by kotaxyz** [comment]
it worked thanks my friend !
